### ISSUE TITLE
toXMLString() tries to modify original object?

### ISSUE THREAD

**Issue by perlguy99** [gcharita/XMLMapper#17]
I'm having an issue when using `toXMLString()` on objects that are in a Realm DB.

It seems that by calling `toXMLString()` on an object that is XMLMappable, the `mapping(map: XMLMap)`  method for the object is called, which tries to modify the object (even if it is keeping the values the same).

The issue, as far as I know it right now, is that when `mapping` is called, the primary key of my object is attempting to be changed, and that causes Realm to crash.

Is there a way to call `toXMLString()` without it attempting to modify any of the existing data?

**Comment by gcharita** [comment]
@perlguy99 thank you for pointing this out. Indeed, because XMLMapper is almost entirely based on [ObjectMapper](https://github.com/tristanhimmelman/ObjectMapper) the following note in [ObjectMappers' README](https://github.com/tristanhimmelman/ObjectMapper#objectmapper--realm) about Realm applied also in XMLMapper:

> Note: Generating a JSON string of a Realm Object using ObjectMappers' toJSON function only works within a Realm write transaction. This is caused because ObjectMapper uses the inout flag in its mapping functions (<-) which are used both for serializing and deserializing. Realm detects the flag and forces the toJSON function to be called within a write block even though the objects are not being modified.

So, the best and more elegant workaround for this issue that I found is to change the mapping of just the primary key.

For example if your primary key is an `id` property use the following code in `mapping(map:)` function just for this property:

```swift
func mapping(map: XMLMap) {
    switch map.mappingType {
    case .fromXML:
        id <- map["id"]
    case .toXML:
        id >>> map["id"]
    }
}
```

This will ensure that the `<-` operator function with the inout flag will called only when you map an XML to your object and never when you call `toXMLString()` function.

Hope this helps.

**Comment by perlguy99** [comment]
THANK YOU!  This was exactly what I was looking for!
