### ISSUE TITLE
Parse failing when illegal characters are present

### ISSUE THREAD

**Issue by SteynMarnus** [gcharita/XMLMapper#20]
I have an XML Mappable Object that I use to map responses from our API:

`class CreateAccountResponse: XMLMappable {
    var nodeName: String!
    
    var Result: String!
    var ResultExplanation: String!
    
    required init?(map: XMLMap) {
        nodeName = ApiConstants.XMLRootTag
    }
    
    func mapping(map: XMLMap) {
        Result <- map["Result"]
        ResultExplanation <- map["ResultExplanation"]
    }`

and I'm using the Alamofire Requests subspec:

`Alamofire.request(ApiProvider.buildUrl(), method: .post, parameters: requestObject.toXML(), encoding: XMLEncoding.default, headers: ApiConstants.Header)
                    .responseXMLObject { (resp: DataResponse<CreateAccountResponse>) in {...}`

And this works just perfect. Here is a example of and XML response that works:

`<API3G>
    <Result>999</Result>
    <ResultExplanation>Email already in use</ResultExplanation>
</API3G>
`

But the same endpoint with the same XML structure, but different values fails to map:

`<API3G> 
    <Result>902</Result>
    <ResultExplanation>Data mismatch in one of the fields - CustomerPassword. Please enter at least 6 characters (letters, numbers and !@#$%&()?)</ResultExplanation>
</API3G>`

The error message I'm getting is as follow: "XMLMapper failed to serialize response."

**Comment by gcharita** [comment]
@SteynMarnus the illegal characters **cannot** be parsed by the [XMLParser](https://developer.apple.com/documentation/foundation/xmlparser) and **must** be XML encoded. [Here](https://stackoverflow.com/a/730150/6791677) is a great stackoverflow answer regarding this.

So, the response should be something like this:

```xml
<API3G>
    <Result>902</Result>
    <ResultExplanation>Data mismatch in one of the fields - CustomerPassword. Please enter at least 6 characters (letters, numbers and !@#$%&amp;()?)</ResultExplanation>
</API3G>
```

Also a tip regarding your model class `CreateAccountResponse`. Since this is a response you do not have to set the `nodeName` property by yourself. XMLMapper have the responsibility to do it for you. You may change you model class to something simpler like:

```swift
class CreateAccountResponse: XMLMappable {
    var nodeName: String!
    
    var Result: String!
    var ResultExplanation: String!
    
    required init?(map: XMLMap) {}
    
    func mapping(map: XMLMap) {
        Result <- map["Result"]
        ResultExplanation <- map["ResultExplanation"]
    }
}
```

Hope this helps.
