### ISSUE TITLE
Ordered XML Attributes

### ISSUE THREAD

**Issue by jinsit** [gcharita/XMLMapper#28]
When I write to XML string, I want to be in order attributes. How do I do this?

example: 
```swift
class TestOrderedAttributes: XMLMappable {
   var NodeName: String!
   var attribute1: String?
   var attribute2: String?
   var attribute3: String?

   init() {}
   required init?(map:XMLMap) {}

   func mapping(map: XMLMap) {
      attribute1 <- map.attributes["attribute1"]
      attribute2 <- map.attributes["attribute2"]
      attribute3 <- map.attributes["attribute3"]
   }
}

let testOrderedAttributes = TestOrderedAttributes()
testOrderedAttributes.attribute1 = "1"
testOrderedAttributes.attribute2= "2"
testOrderedAttributes.attribute3 = "3"
testOrderedAttributes.attributesOrder = ["attribute3", "attribute2", "attribute1"]

```

**Comment by gcharita** [comment]
Hi @jinsit. This is an interesting new feature. I will take a look if this is possible.

**Comment by gcharita** [comment]
@jinsit according to XML documentation, attributes ordering does not matter. (see [this](https://stackoverflow.com/a/57757267/6791677) stackoverflow response)

Also, due to platform limitation we cannot preserve the order of the attributes in **deserialization** of XML data. In the delegate function `parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)` of `XMLParserDelegate` the `attributes` parameter is a dictionary. Starting from Swift 4.2, dictionaries are highly likely to have different order each time you run your app.

So, the only thing we **can** do is to enforce specific order for attributes in **serialization** of a `XMLMappable` object. (although as I said this does not matter)

If you insist that you need this functionality you can try installing XMLMapper from branch `feature/ordered-attributes` using this line in your `Podfile`:
```ruby
pod 'XMLMapper', :git => 'https://github.com/gcharita/XMLMapper.git', :branch => 'feature/ordered-attributes'
```

**Comment by jinsit** [comment]
I write xml file with many attributes in my apps. So when I read xml file later, this feature is necessary for readable xml file. Thanks @gcharita
