### ISSUE TITLE
Update to Alamofire 5

### ISSUE THREAD

**Issue by RalfK92** [gcharita/XMLMapper#31]
Any plans for supporting Alamofire 5?

**Comment by gcharita** [comment]
@RalfK92 thanks for asking.
I do plan to add support for the latest official version of Alamofire, but I currently have a tough schedule.
Feel free to open a PR if you are in a hurry or else stay tuned for the next release.

**Comment by RalfK92** [comment]
It's good, to hear, that you are planning to support Alamofire 5. Maybe if i have time i will try to assist with a PR.

**Comment by embassem** [comment]
any updates for Alamofier 5, now they have released version 5.4 ?

**Comment by gcharita** [comment]
@embassem thanks for asking. I think this feature almost finished (pull request #32)

Since this will be a breaking change (support for Alamofire v4.9 will stop) I would like to also introduce the **CDATA serialization** feature that has been discussed in issue #14. (also implemented in [this](https://github.com/gcharita/XMLMapper/tree/enhancement/cdata-mapping) branch)

A new version will be released in the coming days. 

Thanks for your patience.
