### ISSUE TITLE
Question regarding dots in value

### ISSUE THREAD

**Issue by PatrickB100** [gcharita/XMLMapper#37]
Hi Gcharita,

- I'm having the following issue, a have a mapping where i have a dot in between a single value. Is this a bug or not? if so, is there a workaround?

This code is not working, there is a dot in the middle of LINE.NAME
```
func mapping(map: XMLMap) {
            lineName <- map["LINE.NAME"]
```

This code is fully working. There is no dot in the middle of LINENAME
```
func mapping(map: XMLMap) {
            lineName <- map["LINENAME"]
```

thanks in advance,

Patrick

**Comment by gcharita** [comment]
@PatrickB100 this occurs because of the nested mapping feature. By default dot is the delimiter used to separate the XML element names.

If you have elements with a dot in the name you can override this delimiter (with something that does not appear in the element name)  using `subscript(key:delimiter:)` function of `XMLMap` like so:

```swift
func mapping(map: XMLMap) {
    // use "@" for delimiter
    lineName <- map["LINE.NAME", delimiter: "@"]
}
```

**Comment by PatrickB100** [comment]
@gcharita Thanks! that made sense. it's working fine now.
