### ISSUE TITLE
Parsing fails if innerText contains elements

### ISSUE THREAD

**Issue by sewalsh** [gcharita/XMLMapper#4]
Example fragment:

```
<p eId="para_3">
 Deputy <b>Sherrif</b> is going to rule this town.
</p>
```

This fails due to the `<b>` element being a substring of the innerText.

**Comment by gcharita** [comment]
Parsing not actually fails but creates a difficult to map dictionary. (due to element presence in inner text)

Inner text of an element have to be XML encoded. This XML will be parsed correctly:

```xml
<root>
    <p eId="para_3">
        Deputy &lt;b&gt;Sherrif&lt;/b&gt; is going to rule this town.
    </p>
</root>
```

If you can't change the provided XML you can use the following code to map it as a workaround:

```swift
class RootObject: XMLMappable {
    var nodeName: String!
    
    var pObject: PObject?
    
    required init(map: XMLMap) {
        
    }
    
    func mapping(map: XMLMap) {
        pObject <- map["p"]
    }
}

class PObject: XMLMappable {
    var nodeName: String!
    
    var eId: String?
    var b: String?
    var text: [String]?
    
    required init(map: XMLMap) {
        
    }
    
    func mapping(map: XMLMap) {
        eId <- map.attributes["eId"]
        b <- map["b"]
        text <- map.innerText
    }
}
```

This is not perfect but you can get the information that you want. (although in a difficult to read format)
